[project]
name = "ocpm4lca"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.3.2",
    "plotly>=6.0.0",
    "pm4py>=2.7.13.1",
]
